id: A88D0BDC7
title: 'The Sound of the Divine Drum: Advice at a Time of Victory'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.427608
  last_modified_at: 2022-03-01 00:20:31.427611
