id: A88D0BDC7
title: Upon Arriving at Yangleshö
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.437153
  last_modified_at: 2022-03-01 00:20:31.437157
