id: A88D0BDC7
title: 'The Spontaneous Sound of Uncontrived Song: A Lament Recalling the Great Guru
  of Oḍḍiyāna'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.429206
  last_modified_at: 2022-03-01 00:20:31.429209
