id: A88D0BDC7
title: Aspiration to be Cared For in Every Lifetime
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.403020
  last_modified_at: 2022-03-01 00:20:31.403023
