id: A88D0BDC7
title: Offering to the Dharma Guardians of the 'Neck-Pouch Dagger’ (Purba Gulkhukma)
  Cycle
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.409279
  last_modified_at: 2022-03-01 00:20:31.409282
