id: A88D0BDC7
title: 'A Lament of Faith: A Short Remembrance of, and Prayer to, My Guru, the Wish-Fulfilling
  Jewel'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.388787
  last_modified_at: 2022-03-01 00:20:31.388815
