id: A88D0BDC7
title: A Sādhana of Kurukullā from the Tidro Dharma Cycle
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.390584
  last_modified_at: 2022-03-01 00:20:31.390587
