id: A88D0BDC7
title: 'The Swift Bestowal of Blessings: A Guru Yoga'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.433685
  last_modified_at: 2022-03-01 00:20:31.433688
