id: A88D0BDC7
title: Prayer for the Long Life of Khandro Tāre Lhamo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.411604
  last_modified_at: 2022-03-01 00:20:31.411607
