id: A88D0BDC7
title: 'A Yogi’s Song of Happiness: The Melody that Brings Universal Auspiciousness
  and Fulfilment'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.394171
  last_modified_at: 2022-03-01 00:20:31.394177
