id: A88D0BDC7
title: 'The Healing Medicine of Faith: A Prayer to the Lineage of the Peaceful Sādhana
  of Mañjuśrī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.421574
  last_modified_at: 2022-03-01 00:20:31.421577
