id: A88D0BDC7
title: 'The Cintāmaṇi (Wish-Fulfilling Jewel) Instruction: A Sādhana of the Glorious
  Vajrasattva, a Method of Purification and Accomplishment for Both Self and Others'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.419993
  last_modified_at: 2022-03-01 00:20:31.419998
