id: A88D0BDC7
title: Prayer for the Long Life of His Holiness the Dalai Lama
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.410298
  last_modified_at: 2022-03-01 00:20:31.410301
