id: A88D0BDC7
title: 'Bestowing the Splendour of All That is Desirable: Fire Offering for the ''Neck-Pouch
  Dagger’ (Purba Gulkhukma) Cycle'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.404456
  last_modified_at: 2022-03-01 00:20:31.404459
