id: A88D0BDC7
title: Prayer to Khenchen Jigme Phuntsok
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.413755
  last_modified_at: 2022-03-01 00:20:31.413757
