id: A88D0BDC7
title: Aspiration for the Spread of the Teachings of the Eight Chariots of the Practice
  Lineage
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.401240
  last_modified_at: 2022-03-01 00:20:31.401245
