id: A88D0BDC7
title: 'The Swift Infusion of Blessings: A Lineage Prayer for the Single Mind Kīla
  Heart-Practice, Part of the ''Neck Pouch Dagger’ (Purba Gulkhukma) Cycle'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.435001
  last_modified_at: 2022-03-01 00:20:31.435005
