id: A88D0BDC7
title: 'Accomplishing All Activity: A Daily Practice of the Great and Glorious Dorje
  Drolö'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.396160
  last_modified_at: 2022-03-01 00:20:31.396163
