id: A88D0BDC7
title: Prayer to the Chain of Rebirths
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.414812
  last_modified_at: 2022-03-01 00:20:31.414814
