id: A88D0BDC7
title: Aspiration Prayer
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.397376
  last_modified_at: 2022-03-01 00:20:31.397379
