id: A88D0BDC7
title: 'The Sun of Samantabhadra’s Realm: The Quintessence of Oceanic Prayers of Aspiration'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.430673
  last_modified_at: 2022-03-01 00:20:31.430675
