id: A88D0BDC7
title: 'The Sunlight of Blessings: A Prayer'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:20:31.432398
  last_modified_at: 2022-03-01 00:20:31.432400
